Repository stolostron/installer-dev-tools, pull requests merged in 2025-02, with the labels that each got.

#53 Added linting workflow for repo scripts
  .github/workflows/lint-py.yml
  .github/workflows/lint-shell.yml
  scripts/aks/create-aks.sh
  scripts/aks/delete-aks.sh
  scripts/compliance/pod-enforce.sh
  scripts/compliance/pod-linter.sh
  scripts/release/release-version.sh
Labels: approved

#54 [ACM-17652] Added support for PVC storageClassName value override
  bundle-generation/generate-charts.py
  scripts/bundle_generation/helm_to_customized_helm_charts.py
Labels: approved, lgtm

#59 flight control enhancement
  bundle-generation/generate-charts.py
Labels: approved, lgtm, do-not-merge/hold

#60 [ACM-17894] Added support for olm bundle webhookdefinitions in CSV resource
  bundle-generation/bundles-to-charts.py
  scripts/bundle_generation/olm_bundles_to_helm_charts.py
Labels: approved

#62 [ACM-17894] Added support for webhook_paths configuration
  bundle-generation/bundles-to-charts.py
  scripts/bundle_generation/helper.py
  scripts/bundle_generation/olm_bundles_to_helm_charts.py
Labels: approved
